# imports

import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import sqlalchemy
import os
import datetime
from datetime import timedelta
import csv
import string


# initializations

s = Service(r"C:/Users/voisk/Documents/chromedriver/chromedriver.exe")
driver = webdriver.Chrome(service = s)
#chrome_driver_path = "C:/Users/voisk/Documents/chromedriver/chromedriver.exe"
#driver = webdriver.Chrome(executable_path=chrome_driver_path)

# maximize window

driver.maximize_window()

# lists

sales = []
shop_name = []

# functions, extract info from site

content = driver.page_source
soup = BeautifulSoup(content, "html.parser")


def get_info_sales(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")
        div_element = soup.find("div", {"class": "wt-pt-xs-3"})
        text_content = div_element.text
        text_filter = text_content.replace("Sales", "")
        text_filter_to_int = int(text_filter)
        sales.append(text_filter_to_int)
    except ValueError: 
        try:
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            div_element = soup.find("span", {"class": "wt-text-caption wt-no-wrap"})
            text_content = div_element.text
            text_filter = text_content.replace("Sales", "")
            text_filter2 = text_filter.replace(",", "")
            text_filter_to_int = int(text_filter2)
            sales.append(text_filter_to_int)
        except ValueError:
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            div_element = soup.find("span", {"class": "wt-text-caption wt-no-wrap"})
            text_content = div_element.text
            text_filter = text_content.replace("Sale", "")
            text_filter2 = text_filter.replace(",", "")
            text_filter_to_int = int(text_filter2)
            sales.append(text_filter_to_int)


def get_info_shop_name(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")
        div_element = soup.find("h1", {"class": "wt-text-heading-01 wt-text-truncate"})
        text_content = div_element.text
        shop_name.append(text_content)
    except ValueError:
        soup = BeautifulSoup(response.content, "html.parser")
        div_element = soup.find("h1", {"class": "wt-text-heading-01 wt-text-truncate"})
        text_content = div_element.text
        shop_name.append(text_content)


# store url 507/507 (update here)

get_info_sales("https://www.etsy.com/shop/unidragonpuzzle?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/unidragonpuzzle?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GretaOtoDesign?ref=simple-shop-header-name&listing_id=733759013")
get_info_shop_name("https://www.etsy.com/shop/GretaOtoDesign?ref=simple-shop-header-name&listing_id=733759013")
get_info_sales("https://www.etsy.com/shop/DepleeStore?ref=simple-shop-header-name&listing_id=1370824318")
get_info_shop_name("https://www.etsy.com/shop/DepleeStore?ref=simple-shop-header-name&listing_id=1370824318")
get_info_sales("https://www.etsy.com/shop/OakyLux?ref=simple-shop-header-name&listing_id=1045446537")
get_info_shop_name("https://www.etsy.com/shop/OakyLux?ref=simple-shop-header-name&listing_id=1045446537")
get_info_sales("https://www.etsy.com/shop/personalizedgiftbox?ref=simple-shop-header-name&listing_id=640786982")
get_info_shop_name("https://www.etsy.com/shop/personalizedgiftbox?ref=simple-shop-header-name&listing_id=640786982")
get_info_sales("https://www.etsy.com/shop/DukhaWallArt?ref=shop-header-name&listing_id=857423510")
get_info_shop_name("https://www.etsy.com/shop/DukhaWallArt?ref=shop-header-name&listing_id=857423510")
get_info_sales("https://www.etsy.com/shop/HUNmadeStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HUNmadeStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DayspringPens?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DayspringPens?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AlysaJewelryShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AlysaJewelryShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ArtToyShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ArtToyShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MonettoWoodware?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MonettoWoodware?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BlacKnife?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BlacKnife?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZeekCreativeShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZeekCreativeShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PrintYourHeartOutUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PrintYourHeartOutUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PunoPrints?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PunoPrints?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ClairesAtelierDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ClairesAtelierDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CustomBuiltGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CustomBuiltGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/stayfineofficial?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/stayfineofficial?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/YoursPersonalized?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/YoursPersonalized?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MagnoliaMen?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MagnoliaMen?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/YourNameYourLight?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/YourNameYourLight?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GuardianByKAREN?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GuardianByKAREN?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CraftedLoveInc?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CraftedLoveInc?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SpokenGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SpokenGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JacobDibis?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JacobDibis?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TmolosCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TmolosCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/A1GraphicsLtd?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/A1GraphicsLtd?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AsrinCoDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AsrinCoDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AbegaleWoodenCraftTX?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AbegaleWoodenCraftTX?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CiciJewelryCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CiciJewelryCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngraveForHeart?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngraveForHeart?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Cuttingboarder?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Cuttingboarder?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LaserChimp?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LaserChimp?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AboveStarsArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AboveStarsArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FalkelDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FalkelDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DUCKnDEER?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DUCKnDEER?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CMTImpressions?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CMTImpressions?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ModernTimez?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ModernTimez?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/austero?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/austero?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheChosenOneStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheChosenOneStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SchepperDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SchepperDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodAndSlateGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodAndSlateGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DSGiftStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DSGiftStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZebraHandmadeJewelry?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZebraHandmadeJewelry?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FirstJewelryDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FirstJewelryDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EllenMartinPrints?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EllenMartinPrints?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Myguitartips?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Myguitartips?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FavoriteWoodenGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FavoriteWoodenGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SHANIKStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SHANIKStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ArtAndDelightStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ArtAndDelightStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FavoloseKitchen?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FavoloseKitchen?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BonneStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BonneStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Karniproduction?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Karniproduction?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/lorgie?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/lorgie?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WshopStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WshopStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TigerCoDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TigerCoDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodByStu?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodByStu?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ForestDecorShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ForestDecorShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ExxiDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ExxiDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/UniqueindiacraftShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/UniqueindiacraftShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodPeckerDesignCA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodPeckerDesignCA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CreatzenDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CreatzenDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodpeckerSpain?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodpeckerSpain?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DynamicWorkshop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DynamicWorkshop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EmpireCoolWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EmpireCoolWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LucklaurenArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LucklaurenArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngravedGiftShopUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngravedGiftShopUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ELISAALWONL?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ELISAALWONL?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/KenzByKennie?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/KenzByKennie?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CuttwoodGiftCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CuttwoodGiftCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/YoonekGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/YoonekGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/salvagemevintage?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/salvagemevintage?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheWoodLookGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheWoodLookGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SageandSavoy?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SageandSavoy?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/engraWed?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/engraWed?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SiegosDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SiegosDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngraveYourBoard?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngraveYourBoard?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AnnamarieNix?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AnnamarieNix?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/kikiyoscarves?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/kikiyoscarves?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FEARNOTHING2012?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FEARNOTHING2012?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JustWoodGB?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JustWoodGB?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngraveMyMemories?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngraveMyMemories?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LeePersonalization?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LeePersonalization?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LaundryRoomShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LaundryRoomShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZY89US?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZY89US?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftProShopUS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftProShopUS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheWoodpeckerStudios?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheWoodpeckerStudios?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftsInaJiffy?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftsInaJiffy?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/VoguedesignsAU?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/VoguedesignsAU?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ARRstudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ARRstudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ChillAxDesignShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ChillAxDesignShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Eatartdrink?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Eatartdrink?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZaNaDesignEtsy?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZaNaDesignEtsy?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PBSGiftsAndPrints?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PBSGiftsAndPrints?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RcsFinds?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RcsFinds?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/leftcoastweddings?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/leftcoastweddings?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MoonfaceDigitalPrint?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MoonfaceDigitalPrint?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PersonalizedGiftsEU?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PersonalizedGiftsEU?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JadeKnots?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JadeKnots?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LogoDIY?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LogoDIY?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GreenhappylifeDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GreenhappylifeDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/VertmaxDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/VertmaxDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/kutiecuts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/kutiecuts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LNDPersonalisedGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LNDPersonalisedGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngravologyCreations?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngravologyCreations?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MagicHammerStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MagicHammerStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LeoIvyCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LeoIvyCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/QaliStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/QaliStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftStoryUA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftStoryUA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZehrCustomEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZehrCustomEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JustInCaseBespoke?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JustInCaseBespoke?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TomasStoreCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TomasStoreCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LemongrassENGRAVING?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LemongrassENGRAVING?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HeinzDesignWork?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HeinzDesignWork?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MENECWoodEpoxyArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MENECWoodEpoxyArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/leftcoastoriginal?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/leftcoastoriginal?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LAtelierLaserProduct?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LAtelierLaserProduct?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HottasBottes?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HottasBottes?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZEEMRusticHomeDecor?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZEEMRusticHomeDecor?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SpoonBuddies?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SpoonBuddies?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WildAtlanticWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WildAtlanticWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Brightime?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Brightime?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Frogeral?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Frogeral?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WhisperousWishes?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WhisperousWishes?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngraveManSet?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngraveManSet?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Aestheticsoflife?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Aestheticsoflife?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PremiumGiftsUS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PremiumGiftsUS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LaserPro3D?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LaserPro3D?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CustomGiftsByTaylor?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CustomGiftsByTaylor?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MCKeepsakesGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MCKeepsakesGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheWoodBurningCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheWoodBurningCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MENGCACA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MENGCACA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GearGems?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GearGems?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WOWLYDESIGNS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WOWLYDESIGNS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DownTheLaneDesignsTX?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DownTheLaneDesignsTX?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EthiimoBuildsCanada?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EthiimoBuildsCanada?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PlankRoadDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PlankRoadDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheWOWAT?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheWOWAT?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AJWLeather?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AJWLeather?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MijMojDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MijMojDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EstesDesignStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EstesDesignStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DreamONstudio27?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DreamONstudio27?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MichaelWed?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MichaelWed?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FrankHappiness?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FrankHappiness?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/mineOFwood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/mineOFwood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TreelineAndTide?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TreelineAndTide?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngravedElegancebyG?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngravedElegancebyG?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BadLaser?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BadLaser?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/IntraSStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/IntraSStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodRusticCA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodRusticCA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DesIdeesEnBois?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DesIdeesEnBois?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/yanirahappliques?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/yanirahappliques?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PomchickGift?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PomchickGift?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CyanoWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CyanoWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AZHARYBABA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AZHARYBABA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GLADLYOU?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GLADLYOU?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BigLemur?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BigLemur?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ManhtienCrafts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ManhtienCrafts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodenStudioCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodenStudioCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/jesslovesjoe?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/jesslovesjoe?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MyGiftsUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MyGiftsUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LasersAreUs?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LasersAreUs?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SherlockDesignsAU?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SherlockDesignsAU?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CardsPaperLove?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CardsPaperLove?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/YewCraftyThing?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/YewCraftyThing?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ArtBeaver?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ArtBeaver?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BlueRidgeBoards?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BlueRidgeBoards?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/UniqueDesignMuseum?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/UniqueDesignMuseum?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OakFireCustoms?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OakFireCustoms?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/rusticcraftdesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/rusticcraftdesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EspaceGravure81?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EspaceGravure81?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JONASHOME?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JONASHOME?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JMFine8?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JMFine8?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Coasterboydesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Coasterboydesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/QuoteMyGift?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/QuoteMyGift?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OhWoodenitbelovely?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OhWoodenitbelovely?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LMWoodCraft?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LMWoodCraft?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EMKAworkshop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EMKAworkshop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WittleWoodStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WittleWoodStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodBoxBoutique?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodBoxBoutique?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BrodyandBirch?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BrodyandBirch?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MakeThisMineGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MakeThisMineGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Arbresymbolique?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Arbresymbolique?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BelalGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BelalGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AlittleshopByAlex?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AlittleshopByAlex?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LoveUniquePersonal?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LoveUniquePersonal?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ElegantGift?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ElegantGift?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngravingBrothers?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngravingBrothers?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AlchemyEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AlchemyEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LuckTen?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LuckTen?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SIAxDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SIAxDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BestWoodenStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BestWoodenStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AngieWoodCreationsCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AngieWoodCreationsCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CustomQueenUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CustomQueenUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ideasengraved?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ideasengraved?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodOfKitchen?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodOfKitchen?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CreatedEspForYou?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CreatedEspForYou?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Pyracord?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Pyracord?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngroovyLaser?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngroovyLaser?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PassionifyCO?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PassionifyCO?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LaserCuttsGB?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LaserCuttsGB?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/memoriesforlifesb?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/memoriesforlifesb?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RollingPinCollection?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RollingPinCollection?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OtterandOwlGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OtterandOwlGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/bbeehandcrafted?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/bbeehandcrafted?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Thatsnicethatuk?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Thatsnicethatuk?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/foryou24?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/foryou24?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EverythingEtchedAZ?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EverythingEtchedAZ?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/IVY01CA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/IVY01CA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ShowstopperSupplies?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ShowstopperSupplies?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftLaserForYou?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftLaserForYou?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZagannGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZagannGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TDYArtAtelier?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TDYArtAtelier?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/STEVENGARDINERLTD?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/STEVENGARDINERLTD?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JTStudioDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JTStudioDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MMSTINGER?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MMSTINGER?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SpottedZebraCA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SpottedZebraCA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WeddingIsComing?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WeddingIsComing?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/donebetter?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/donebetter?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Geschenkeschmiede?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Geschenkeschmiede?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ThistleAndSash?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ThistleAndSash?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Studio26Engraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Studio26Engraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TwistedBranchDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TwistedBranchDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MobiusWoodWork?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MobiusWoodWork?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PiperandSageDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PiperandSageDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CustomGiftCoUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CustomGiftCoUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Givenie?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Givenie?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Berbendesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Berbendesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MrandMrsAZ?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MrandMrsAZ?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JJHandmadeGiftsShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JJHandmadeGiftsShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HPCubittsCuriosityCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HPCubittsCuriosityCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GrowandCompany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GrowandCompany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GHKnife?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GHKnife?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WildRibbonDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WildRibbonDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/StudioTimeRebel?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/StudioTimeRebel?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Hotlaser?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Hotlaser?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PannPanda?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PannPanda?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Inakhi?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Inakhi?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CutncraftDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CutncraftDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/byFairyTale?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/byFairyTale?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MelissaGCrafts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MelissaGCrafts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngravedGiftsStudio1?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngravedGiftsStudio1?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/2PersonalShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/2PersonalShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodAndMine?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodAndMine?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheShameless?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheShameless?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OneDapperGent?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OneDapperGent?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LisaAngelLtd?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LisaAngelLtd?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HoneyTheWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HoneyTheWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RoyaltyEngravingGTA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RoyaltyEngravingGTA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/sublimagecreations?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/sublimagecreations?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LunefulleCreations?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LunefulleCreations?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HMDesignsNI?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HMDesignsNI?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Eden5599?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Eden5599?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftsforallDesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftsforallDesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LeezeesHennaStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LeezeesHennaStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Made0in0Germany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Made0in0Germany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DEKOLANDO?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DEKOLANDO?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BritishGoldCompany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BritishGoldCompany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LilyCraftAu?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LilyCraftAu?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/stikaco?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/stikaco?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SwankyBadger?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SwankyBadger?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/trendshopic?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/trendshopic?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BaniCollection?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BaniCollection?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AleenaCreates?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AleenaCreates?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AutumnWoodsCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AutumnWoodsCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/derwatches?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/derwatches?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ArtDesignStudioCy?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ArtDesignStudioCy?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AVANTwatches?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AVANTwatches?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RevivalWoodworking?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RevivalWoodworking?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheDustySaw?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheDustySaw?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Woodinout?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Woodinout?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/tiposcreations?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/tiposcreations?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Tsymbal?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Tsymbal?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/engravisLT?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/engravisLT?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LarchPersonalized?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LarchPersonalized?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CuriousCraftRoom?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CuriousCraftRoom?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AZworkshopART?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AZworkshopART?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/codistrict?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/codistrict?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/zptees?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/zptees?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BfCartMallorca?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BfCartMallorca?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OneTreeWoodwork?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OneTreeWoodwork?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ArtyandLife?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ArtyandLife?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/NewWorldEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/NewWorldEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PersonalisedGifting?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PersonalisedGifting?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BlackCatLasers?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BlackCatLasers?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HydroLabBottles?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HydroLabBottles?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CryptoMerch?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CryptoMerch?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AreoDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AreoDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/YouCanMAKEitPERSONAL?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/YouCanMAKEitPERSONAL?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LithaCreations?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LithaCreations?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Huglot?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Huglot?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PrintSmitten?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PrintSmitten?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AritaGiftStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AritaGiftStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/VectorEngrave?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/VectorEngrave?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FutureRetroGolf?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FutureRetroGolf?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MyPersonalPrintsShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MyPersonalPrintsShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Handmadewoodengifts1?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Handmadewoodengifts1?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TrueMementos?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TrueMementos?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CreativeUseofTech?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CreativeUseofTech?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/IRONandGRAINusa?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/IRONandGRAINusa?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DirectSolutionStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DirectSolutionStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BurninLoveLaser?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BurninLoveLaser?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ByFatema?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ByFatema?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/4EverNGraved?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/4EverNGraved?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PeckerStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PeckerStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PersonalProductLine?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PersonalProductLine?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Dekeswoodshed?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Dekeswoodshed?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LetsEngraveIt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LetsEngraveIt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EPICut?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EPICut?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/glitzzyshop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/glitzzyshop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AvantWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AvantWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Customcuff?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Customcuff?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AlgisCrafts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AlgisCrafts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JorvikWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JorvikWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SundaysDaughterUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SundaysDaughterUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TopPresentForYou?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TopPresentForYou?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/oldoakdesigncompany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/oldoakdesigncompany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AllCraftsCoShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AllCraftsCoShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PrideandPassionShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PrideandPassionShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/NicoleDesignCrafts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/NicoleDesignCrafts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HoneycombProverbs?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HoneycombProverbs?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/patienceandgraceshop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/patienceandgraceshop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BlueCocoaDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BlueCocoaDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DEKLaserDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DEKLaserDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RosaryCatholicStatue?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RosaryCatholicStatue?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SpreadingLoveDecor?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SpreadingLoveDecor?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AkasiaWoodArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AkasiaWoodArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PurrFectEngravers?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PurrFectEngravers?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/alwaysforevermoreuk?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/alwaysforevermoreuk?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DABhandLaserCraft?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DABhandLaserCraft?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/StoneflyStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/StoneflyStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CountryTouchStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CountryTouchStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ForgingsHHsepp?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ForgingsHHsepp?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ReidsEngravables?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ReidsEngravables?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LeottoDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LeottoDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZTenEva?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZTenEva?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EveryRoseUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EveryRoseUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DDandDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DDandDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WonderlandCraftory?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WonderlandCraftory?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CCuttingBoards?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CCuttingBoards?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OpenHausGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OpenHausGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Whitetailwc?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Whitetailwc?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BaffleGearUSA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BaffleGearUSA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WildandMug?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WildandMug?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AgeBoutique?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AgeBoutique?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Luckanov?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Luckanov?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CreatedForMeStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CreatedForMeStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SESHNOTSTIGMA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SESHNOTSTIGMA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WalkSpirit?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WalkSpirit?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/stampoutonline?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/stampoutonline?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CutTheWood?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CutTheWood?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HollyandFred?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HollyandFred?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WallisFamilyCustoms?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WallisFamilyCustoms?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AlegriaByElena?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AlegriaByElena?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RossCarpentryCA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RossCarpentryCA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FureverFarmhouse?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FureverFarmhouse?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ToppLuxx?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ToppLuxx?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MandPDesignCompany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MandPDesignCompany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/designcraftindustrie?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/designcraftindustrie?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/7T6designs?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/7T6designs?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HandMadeMihaylova?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HandMadeMihaylova?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SAYYOURWAYS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SAYYOURWAYS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Etchworthy?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Etchworthy?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BAwoodLV?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BAwoodLV?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BeerSide?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BeerSide?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WilsonsWonders85?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WilsonsWonders85?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Amyjacksoncrafts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Amyjacksoncrafts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SnyderWoodworkingCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SnyderWoodworkingCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ArtWoodenCorner?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ArtWoodenCorner?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GREENHEALTHYHUMAN?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GREENHEALTHYHUMAN?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftIdeasUA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftIdeasUA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MountainWoodWorkCA?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MountainWoodWorkCA?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TreeTownPaper?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TreeTownPaper?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BelfieldTreasures?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BelfieldTreasures?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WolfSpiritGift?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WolfSpiritGift?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HummingbirdGraphix?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HummingbirdGraphix?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/greekshowapparel?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/greekshowapparel?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/southpawscribedesign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/southpawscribedesign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DaniqueTrends?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DaniqueTrends?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiviGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiviGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/3dGeekWares?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/3dGeekWares?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BrassHoncho?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BrassHoncho?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EcolourHomeGoods?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EcolourHomeGoods?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GratitudeJourneyShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GratitudeJourneyShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/KustomProducts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/KustomProducts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WhiddensWoodshop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WhiddensWoodshop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DoughRoller?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DoughRoller?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CGdesignsGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CGdesignsGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OldCatStoreNo13?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OldCatStoreNo13?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/YellowBirdCraftStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/YellowBirdCraftStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DomasCraft?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DomasCraft?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/InterstellarTr?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/InterstellarTr?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DigiPapier?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DigiPapier?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/KlaehnsCreations?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/KlaehnsCreations?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RaynoGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RaynoGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/KiraDesignEngravings?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/KiraDesignEngravings?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Elowvy?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Elowvy?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CherishUs?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CherishUs?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Quasar3DP?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Quasar3DP?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BradysBricks?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BradysBricks?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MirrorManiaDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MirrorManiaDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HCleathergoods?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HCleathergoods?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/eleonorasartworld?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/eleonorasartworld?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DecorDivine?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DecorDivine?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/handmadekanthaitem?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/handmadekanthaitem?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Carvwoodsign?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Carvwoodsign?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/DesignMugStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/DesignMugStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EastcoastKrafters?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EastcoastKrafters?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OrientalMe?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OrientalMe?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/byBlueRidgeEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/byBlueRidgeEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MyCoasterShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MyCoasterShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/crawoo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/crawoo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CarvingRollingPin?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CarvingRollingPin?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/KTeaDesignsLLC?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/KTeaDesignsLLC?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JustCreations2570?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JustCreations2570?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/woodmanucom?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/woodmanucom?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BotanicaWatches?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BotanicaWatches?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JoandCo22?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JoandCo22?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GravisCup?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GravisCup?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodenGiftsBox?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodenGiftsBox?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GreatEngravedGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GreatEngravedGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GlowNion?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GlowNion?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/H39DESIGNS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/H39DESIGNS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/madeinabarncanada?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/madeinabarncanada?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BeehiveCornerCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BeehiveCornerCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodlandWatches?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodlandWatches?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Vectoart?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Vectoart?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodAndBoard?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodAndBoard?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WhosShe?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WhosShe?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodstarMilano?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodstarMilano?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AndAmpersandShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AndAmpersandShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LazerDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LazerDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Modply?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Modply?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GoodVibesLaserShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GoodVibesLaserShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ThirstyRhinoDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ThirstyRhinoDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Wayfaren?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Wayfaren?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RogueFashionStyle?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RogueFashionStyle?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/NEFStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/NEFStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LeoLoveLeather?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LeoLoveLeather?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TreeZoneForYou?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TreeZoneForYou?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Petewave?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Petewave?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WithaCustomTouch?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WithaCustomTouch?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LaserArtMTL?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LaserArtMTL?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/shopneighborwoods?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/shopneighborwoods?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/NightingaleWorksArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/NightingaleWorksArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GiftFactoryUS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GiftFactoryUS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/BrokenBoardDesignCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/BrokenBoardDesignCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ZBStoreCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ZBStoreCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ResWoodDesignsUS?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ResWoodDesignsUS?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RollingPin13?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RollingPin13?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodenGoodsStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodenGoodsStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HazelGroveCustoms?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HazelGroveCustoms?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WunderholzShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WunderholzShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ChunGoodGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ChunGoodGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/AxiomEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/AxiomEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CJKEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CJKEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CraftyPantsDesignCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CraftyPantsDesignCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LegendCustomLaser?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LegendCustomLaser?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/HazelwoodCNC?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/HazelwoodCNC?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LittleWildOneAU?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LittleWildOneAU?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/SelahScriptCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/SelahScriptCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PaulVenStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PaulVenStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CraftedForMemories?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CraftedForMemories?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/harbourlightstudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/harbourlightstudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ChumandCompany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ChumandCompany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ChumandCompany?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ChumandCompany?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/giftsbykoles?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/giftsbykoles?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MadeInSunState?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MadeInSunState?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/laserprintedproducts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/laserprintedproducts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/QualitaCo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/QualitaCo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GustoLeatherDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GustoLeatherDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/CoocoShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/CoocoShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Pressieboo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Pressieboo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/NamiloHome?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/NamiloHome?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WaldWichtShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WaldWichtShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GreatUniqueGiftsUsa?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GreatUniqueGiftsUsa?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LittleWoodpeckerUK?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LittleWoodpeckerUK?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/FunnyBaker?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/FunnyBaker?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Woo1Studio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Woo1Studio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/customization4you?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/customization4you?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EngravedJewelryBox?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EngravedJewelryBox?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LiliDreamsCraft?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LiliDreamsCraft?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WoodlyGift?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WoodlyGift?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/EZCUSTOMGIFT?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/EZCUSTOMGIFT?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PoshDesignStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PoshDesignStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LumiaLanes?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LumiaLanes?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/PersonalisedByPicArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/PersonalisedByPicArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WudmaxStore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WudmaxStore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OMGWorkshop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OMGWorkshop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MountainBornLiving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MountainBornLiving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/UrbanForestEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/UrbanForestEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/KaydenWoodStudio?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/KaydenWoodStudio?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Ledexpression2?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Ledexpression2?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/JarriAtelier?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/JarriAtelier?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/OneStopShopNGo?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/OneStopShopNGo?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RusticRouteDesigns?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RusticRouteDesigns?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/coolNaturalJewelry?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/coolNaturalJewelry?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/WildWatches?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/WildWatches?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/blackeagledesgn?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/blackeagledesgn?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/MunsellMade?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/MunsellMade?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/GoToLuckyShop?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/GoToLuckyShop?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/IRONandGRAINusa?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/IRONandGRAINusa?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/Terrymastore?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/Terrymastore?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/RezBatsEngraving?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/RezBatsEngraving?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/TheCraftCabinArt?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/TheCraftCabinArt?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/LilliMoGifts?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/LilliMoGifts?ref=l2-about-shopname")
get_info_sales("https://www.etsy.com/shop/ItLooksBeautiful?ref=l2-about-shopname")
get_info_shop_name("https://www.etsy.com/shop/ItLooksBeautiful?ref=l2-about-shopname")

# agree cookies

#agree = driver.find_element("xpath", '//button[@class="wt-btn wt-btn--filled wt-mb-xs-0"]')

#try:
#    agree.click()
#except:
#    pass

print("Today sales:", sales) # view info
print("Shop names:", shop_name) # view info

# saving file

file = pd.DataFrame()
date = datetime.datetime.now()
date2 = date.strftime("%d %b, %Y")
file.to_csv(f"{date2}.csv", index = False, encoding='utf-8')

# info to file

header = ["Shop name", "Sales", "Sales per day"]
data = []

with open(f"{date2}.csv", "w", encoding = "utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(header)


def write_info_to_file():
    data.clear()
    data.append(shop_name[0])
    data.append(sales[0])
    shop_name.pop(0)
    sales.pop(0)
    with open(f"{date2}.csv", "a", encoding = "utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(data)
        

# starting def write info to file

deleting = 0
while deleting < len(sales):
   write_info_to_file()

# day statistics

day_file = pd.read_csv(f"{date2}.csv")

day_sales_list = day_file.Sales

sales_from_day = []

for day_sale in day_sales_list:
    sales_from_day.append(day_sale)

# one day sales

general_sales_stats = []

# creating yesterday date

date3 = date - timedelta(days = 1)
date4 = date3.strftime("%d %b, %Y")
data_from_yesterday = pd.read_csv(f"{date4}.csv")

# saving yesterday sales to list

yesterday_list = []
yesterday_list = data_from_yesterday["Sales"].to_list()

# saving sales statistic to list

for day_results in range(len(sales_from_day)):
    general_results = sales_from_day[day_results] - yesterday_list[day_results]
    general_sales_stats.append(general_results)

print("Sales differents:", general_sales_stats) # view info
print("Yesterday sales:", yesterday_list) # view info

# add new list with day sales to file

day_file["Sales per day"] = general_sales_stats

# finish saving

day_file.to_csv(f"{date2}.csv", index = False, encoding='utf-8')